In [1]:
import numpy as np

In [2]:
data=np.random.randn(2,3)

In [3]:
data

array([[-3.11413606, -2.12224474, -0.20967056],
       [-1.19101142,  1.17207596,  0.56260564]])

In [4]:
data*10

array([[-31.14136059, -21.22244745,  -2.09670562],
       [-11.91011418,  11.72075962,   5.62605643]])

In [5]:
data+data

array([[-6.22827212, -4.24448949, -0.41934112],
       [-2.38202284,  2.34415192,  1.12521129]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

In [8]:
data1=[6,7.5,8,0,1]

In [9]:
arr1=np.array(data1)

In [10]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
data2=[[1,2,3,4],[5,6,7,8]]

In [14]:
arr2=np.array(data2)

In [15]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2.ndim

2

In [17]:
arr2.shape

(2, 4)

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
np.ones_like(arr2)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [22]:
(np.arange(15)).astype('float64')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [26]:
arr=np.array([[1.,2.,3.],[4.,5.,6.]])

In [27]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [30]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [32]:
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])

In [33]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [34]:
arr=np.arange(10)

In [35]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr[5]

5

In [37]:
arr[5:8]

array([5, 6, 7])

In [39]:
arr[5:8]=12

In [40]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [41]:
arr_slice=arr[5:8]

In [42]:
arr_slice

array([12, 12, 12])

In [54]:
arr_slice[:]=12345

TypeError: 'int' object does not support item assignment

In [51]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [55]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [56]:
arr2d[2]

array([7, 8, 9])

In [57]:
arr2d[0][2]

3

In [58]:
arr2d[0,2]

3

In [59]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [60]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
old_values=arr3d[0].copy()

In [63]:
arr3d[0]=42

In [64]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [65]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [66]:
arr2d[1,:2]

array([4, 5])

In [67]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [42]:
names=np.array(['Bob','Joe','Wil1','Bob','Wil1','Joe','Joe'])

In [79]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [80]:
data=np.random.randn(7,4)

In [81]:
data

array([[-1.27429385, -0.05226225,  1.8859841 ,  0.68821814],
       [-0.08572966,  0.69245915, -0.49427254,  1.52642931],
       [-0.41564123,  1.33812859, -1.17250012, -0.42941362],
       [-0.90952996, -1.42644072, -1.07270293,  1.63656882],
       [ 0.19401139,  0.85707795, -0.51146204,  0.58351984],
       [ 0.72340498, -0.88330975, -1.15883834,  0.90497727],
       [-0.26174448,  1.30204399, -0.59523837,  0.93151742]])

In [82]:
data[(names=='Bob'),:]

array([[-1.27429385, -0.05226225,  1.8859841 ,  0.68821814],
       [-0.90952996, -1.42644072, -1.07270293,  1.63656882]])

In [84]:
cond= names=='Bob'

In [85]:
data[~cond]

array([[-0.08572966,  0.69245915, -0.49427254,  1.52642931],
       [-0.41564123,  1.33812859, -1.17250012, -0.42941362],
       [ 0.19401139,  0.85707795, -0.51146204,  0.58351984],
       [ 0.72340498, -0.88330975, -1.15883834,  0.90497727],
       [-0.26174448,  1.30204399, -0.59523837,  0.93151742]])

In [86]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [87]:
arr=np.arange(15).reshape((3,5))

In [88]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [89]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [90]:
arr.dot(arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [91]:
arr=np.arange(16).reshape((2,2,4))

In [92]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [93]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [94]:
arr=np.arange(10)

In [95]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [97]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [98]:
np.max(arr)

9

In [100]:
arr_=np.random.randint(5,15,10)
arr_

array([ 6,  7,  9,  8,  6, 11,  9,  8,  9, 14])

In [101]:
np.maximum(arr,arr_)

array([ 6,  7,  9,  8,  6, 11,  9,  8,  9, 14])

In [5]:
points=np.arange(-5,5,0.01)
points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [3]:
xs,ys=np.meshgrid(points,points)

In [4]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [6]:
xarr=np.array([1.1,1.2,1.3,1.4,1.5])

In [7]:
yarr=np.array([2.1,2.2,2.3,2.4,2.5])

In [8]:
cond=np.array([True,False,True,True,False])

In [9]:
result=[(x if c else y) for x,y,c in zip(xarr,yarr,cond)]

In [10]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [11]:
result=np.where(cond,xarr,yarr)

In [12]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [13]:
arr=np.random.randn(5,4)

In [14]:
arr

array([[ 0.85394812, -1.26192284, -1.20707017, -2.63899122],
       [-0.26673328, -0.1420501 , -0.97619582, -1.41943871],
       [ 1.67138807,  1.22456314, -2.07673169, -0.303722  ],
       [-0.87097759, -0.51325319,  1.43713166, -0.12801347],
       [ 1.11564429, -1.21185868,  1.04854271,  2.47412273]])

In [15]:
arr.mean()

-0.15958090245815285

In [16]:
np.mean(arr)

-0.15958090245815285

In [17]:
arr.sum()

-3.191618049163057

In [19]:
arr.mean(axis=1)#按行计算

array([-1.06350903, -0.70110448,  0.12887438, -0.01877815,  0.85661276])

In [20]:
arr.sum(axis=0)#按列计算

array([ 2.5032696 , -1.90452167, -1.77432331, -2.01604267])

In [21]:
arr.argmax()

19

In [24]:
arr.max()

2.474122725340468

In [25]:
arr>0

array([[ True, False, False, False],
       [False, False, False, False],
       [ True,  True, False, False],
       [False, False,  True, False],
       [ True, False,  True,  True]])

In [26]:
(arr>0).sum()

7

In [27]:
(arr>0).any()

True

In [28]:
(arr>0).all()

False

In [29]:
(arr>3).any()

False

In [30]:
(arr<3).all()

True

In [36]:
arr=np.random.randn(6)
arr

array([-0.45213265,  0.28523348,  1.38245959,  0.02061951, -1.21807211,
       -0.78455821])

In [37]:
arr.sort()
arr

array([-1.21807211, -0.78455821, -0.45213265,  0.02061951,  0.28523348,
        1.38245959])

In [38]:
arr=np.random.randn(4,5)

In [39]:
arr

array([[ 0.02162953,  0.85576274, -1.19404724,  0.15514334, -1.6195781 ],
       [-0.23031558, -2.14417996, -0.20520968,  2.40133784,  1.50641937],
       [ 1.23874899,  0.78544896, -0.94705964, -1.33668233,  2.57789197],
       [ 0.45690753, -0.39060308,  1.26082783,  0.84568622,  0.72449287]])

In [40]:
arr.sort(axis=1)

In [41]:
arr

array([[-1.6195781 , -1.19404724,  0.02162953,  0.15514334,  0.85576274],
       [-2.14417996, -0.23031558, -0.20520968,  1.50641937,  2.40133784],
       [-1.33668233, -0.94705964,  0.78544896,  1.23874899,  2.57789197],
       [-0.39060308,  0.45690753,  0.72449287,  0.84568622,  1.26082783]])

In [45]:
np.unique(names)

array(['Bob', 'Joe', 'Wil1'], dtype='<U4')